### PR TITLE
Update dl_vlan validation to allow mask

### LINKED ISSUE #132: feat: support FlowMod matching vlan with mask
This is for supporting matching a range of vlans that mef_eline VLAN feature will need https://github.com/kytos-ng/mef_eline/issues/18

We have some fields with mask support but some are crashing as mentioned on issue #24 

API docs should also be updated

This issue will still be refined

### PR DESCRIPTION
**Pull request by ajoaoff**
Closes #132 

- Accept `dl_vlan` in the format `vlan/mask` in addition to `vlan`

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
@ajoaoff looks good to me. 

Could you update the changelog? Also, could you provide either a migration MongoDB command in the changelog itself if it's short, or a migration script updating/mapping `dl_vlan` values as string? This change would break anything but it would leave different types in the collection that can become confusing, `2022.3.X` will be used in production at AmLight, thanks.

**Review by Alopalao — APPROVED** [review]

**Comment by Alopalao** [comment]
This PR also handles `any` and `untagged` cases I am working on.

**Review by viniarck — APPROVED** [review]
LGTM. Thanks for also pushing this script @ajoaoff. 

Antonio, before merging, let's also update the changelog, if you can also mention there about this script that'd be great. @italovalcy when AmLight upgrades to `2023.1` some months down the road you'll probably want to run this script.

**Comment by italovalcy** [comment]
@viniarck and @ajoaoff, since this is a major change that will impact other Napps, IMO we have to increase the API version and keep the old one compatible with the previous format—maybe providing an abstraction between the two versions (which will convert int to string).

Another strategy would be supporting both int and string.

WDYT?

**Comment by Alopalao** [comment]
Good point. If we decide to unify the string format for `dl_vlan`, `of_core` will be affected since the `vlan_id` is returned as int ([here](https://github.com/kytos-ng/of_core/blob/898872f4aeddca84a524f1cc9ef61e5b92b0cccc/v0x04/match_fields.py#L58)). Combination of int and string is already supported, [here](https://github.com/kytos-ng/of_core/blob/898872f4aeddca84a524f1cc9ef61e5b92b0cccc/v0x04/match_fields.py#L61) it is returned as string.

**Comment by viniarck** [comment]
> @viniarck and @ajoaoff, since this is a major change that will impact other Napps, IMO we have to increase the API version and keep the old one compatible with the previous format—maybe providing an abstraction between the two versions (which will convert int to string).
> 
> Another strategy would be supporting both int and string.
> 
> WDYT?

@italovalcy you're right, we do need to bump v3, but, since we still have changes to make on `flow_manager`s API like other validations in general issue https://github.com/kytos-ng/flow_manager/issues/43 (`cookie_mask` mandatory for deletions an so on), then we could leave to bump v3 in this linked issue. That way, in this current issue here we just unblock what `mef_eline` any/untagged and vlan range need that this PR is delivering allowing the team to still make progress in parallel, and the good news is that it didn't completely broke API compatibility yet (although it's already officializing it on the openapi.yml spec), the way @ajoaoff implemented the DB validator `vlan_with_mask` for `dl_vlan` it stills parses correctly it an int is passed down, so NApps can still use their payload as they have in the meantime during development, except `sdntrace_cp` that indeed relies how `dl_vlan` is stored. But then the only caution in the meantime is to avoid mixing sending the same flow with `dl_vlan` as `int` or `str(int)`, since we don't have API validation yet, then their `match_id` and `id` will still be different and the consistency check will result in a false positive keep trying to install an existing flow (in a case where a NApp is pushing flows).

To avoid the potential issue mentioned in the prior paragraph, I agree with you Italo that we could provide a tiny validation converting any `dl_vlan` that is an int as a `str` for both `@listen_to("kytos.flow_manager.flows.(install|delete)")` and `POST|DELETE v2/flows` in the meantime, @ajoaoff could you also cover this part please? A function/method mapping the payload should suffice, and then we we land the rest of the validations on issue #43 we drop this specific `dl_vlan` validation that will be introduced here, wdyt guys?

**Comment by viniarck** [comment]
Agreed @italovalcy @Alopalao, I tend to avoid mixing different type for the same field `dl_vlan`, but it's becoming evident that `dl_vlan` being `Optional[Union[str, int]]` would make things way simpler, and only use a str when setting a mask as `of_core` has been designed, not completely breaking compatibility with the API as well while extending it to support the mask. @ajoaoff could you adapt this part? That way we also wouldn't need the script as well. Thanks

Regarding bumping v3 though, let's leave it to when we address the other validations in general on issue https://github.com/kytos-ng/flow_manager/issues/43 that we have on our radar (`cookie_mask` mandatory for deletions an so on).

**Review by viniarck — APPROVED** [review]
@ajoaoff thanks for this PR and pushing the latest commits. I went ahead and finished reverting the scripts related changes and updated the changelog just so this PR can get merged right away unblocking also mef_eline uni any/untagged feature that @Alopalao is working on.

**Pull request merged**
