### PR TITLE
Added validator for `actions` and `instructions`

### LINKED ISSUE #159: Flow top level `instructions` and `actions` (historic OF1.0 format) should be mutually exclusive
Historically, most NApps have been using `actions`, which on OF1.3 context, it'll be converted as OF FlowMod instruction when being serialized, but we've been also supporting `actions` to avoid breaking APIs and having to change NApps that use this format. There's no issues or harm to still use `actions` in the old format, and it'll be maintained, but it should be mutually exclusive with `instructions`, otherwise it can result in `OFPT_ERROR`:

Example of invalid payload:

```
{
    "force": false,
    "flows": [
        {
            "priority": 38000,
            "match": {
                "in_port": 1,
                "dl_vlan": 1004
            },
            "instructions": [
                {
                    "instruction_type": "apply_actions",
                    "actions": [
                        {
                            "action_type": "output",
                            "port": 10
                        }
                    ]
                }
            ],
            "actions": [
                {
                    "action_type": "output",
                    "port": 11
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by Alopalao**
Closes #159 

### Summary
When adding a flow, `actions` and `instructions` should not be present at the same time.

### Local Tests
Created requests with `actions` and `instructions` in the same flow.
Added uni tests

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
Excellent to have this improved validation, Aldo. 

Looks great to me. The changelog hasn't been updated though. 

Other than that if you could also map and implement the two extra tasks that we discussed in the issue that'd be great to have them covered on `2023.2` too (they are lower priority compared to the other epics your working on though, so add to your list as you have capacity). Currently, `flow_manager` is still vulnerable if multiple repeated instruction_type is sent on instructions (it'll probably be easier to validate on flow_manager for now instead of `pyof` based on how each item is passed to instructions).

**Review by viniarck — CHANGES_REQUESTED** [review]
Changelog hasn't been updated yet

**Comment by Alopalao** [comment]
Sorry I totally forgot about it, changelog updated and resolved some merge conflicts.

**Comment by viniarck** [comment]
> Sorry I totally forgot about it, changelog updated and resolved some merge conflicts.

Appreciated the updates, Aldo. It'll get merged soon since `2023.1` has just been tagged.

**Pull request merged**
