### PR TITLE
[Fix] Consistency check to run immediately when FlowStats is first received

### LINKED ISSUE #114: After an OF handshake, consistency check might end up skipping a consistency check cycle
This is a corner case that's happening:

After an OF handshake, consistency check might end up skipping a consistency check cycle. It turns out that `flow_manager` [is resetting the `flow_checks` entry](https://github.com/kytos-ng/flow_manager/blob/master/main.py#L139), but we need to pass down to other related methods that it should execute without skipping, otherwise it would always consider the `CONSISTENCY_MIN_VERDICT_INTERVAL`, and as a result, it would skip one extra initial cycle. 

The desired behavior is after an OF handshake and once FlowStats reply is received consistency check should run (I've also confirmed that this is aligned with AmLight's use case) even if `CONSISTENCY_MIN_VERDICT_INTERVAL` hasn't passed.

### PR DESCRIPTION
**Pull request by viniarck**
Fixes #114 

- Fixed consistency check to run immediately when FlowStats is first received.

### Using this branch

- Once FlowStats is first received and consistency check started, after 4ms in the same cycle, it detected a missing flow:

```
kytos $> 2022-10-24 11:02:58,745 - INFO [kytos.core.atcp_server] [atcp_server.py:131:connection_made] (MainThread) New connection from 127.0.0.1:57598
2022-10-24 11:02:58,746 - INFO [kytos.core.atcp_server] [atcp_server.py:182:connection_lost] (MainThread) Connection lost with client 127.0.0.1:57598. Reason: Request closed by client
2022-10-24 11:02:58,851 - INFO [kytos.core.atcp_server] [atcp_server.py:131:connection_made] (MainThread) New connection from 127.0.0.1:57612
2022-10-24 11:02:58,858 - INFO [kytos.napps.kytos/of_core] [main.py:138:handle_features_reply] (thread_pool_sb_0) Connection ('127.0.0.1', 57612), Switch 00:00:00:00:00:00:00:01: OPENFLO
W HANDSHAKE COMPLETE
2022-10-24 11:02:58,877 - INFO [kytos.napps.kytos/flow_manager] [main.py:571:_send_flow_mods_from_request] (Thread-93) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command: a
dd, force: False, flows_dict: {'flows': [{'priority': 1000, 'table_id': 0, 'cookie': 12321848580485677057, 'match': {'dl_type': 35020, 'dl_vlan': 3799}, 'actions': [{'action_type': 'outp
ut', 'port': 4294967293}]}]}
2022-10-24 11:02:58,887 - INFO [werkzeug] [_internal.py:225:_log] (Thread-93) 127.0.0.1 - - [24/Oct/2022 11:02:58] "POST /api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01 HTTP/1.1
" 202 -
2022-10-24 11:03:00,380 - INFO [kytos.napps.kytos/flow_manager] [main.py:333:check_consistency] (thread_pool_sb_2) check_consistency on switch 00:00:00:00:00:00:00:01 has started
2022-10-24 11:03:00,384 - INFO [kytos.napps.kytos/flow_manager] [main.py:361:check_missing_flows] (thread_pool_sb_2) Consistency check: missing flow on switch 00:00:00:00:00:00:00:01.
2022-10-24 11:03:00,385 - INFO [kytos.napps.kytos/flow_manager] [main.py:365:check_missing_flows] (thread_pool_sb_2) Flow forwarded to switch 00:00:00:00:00:00:00:01 to be installed. Flo
w: {'flows': [{'cookie': 0, 'match': {'in_port': 1, 'dl_vlan': 105}, 'actions': [{'action_type': 'output', 'port': 1}], 'table_id': 0, 'priority': 101, 'idle_timeout': 0, 'hard_timeout':
 0}]}
2022-10-24 11:03:00,385 - INFO [kytos.napps.kytos/flow_manager] [main.py:336:check_consistency] (thread_pool_sb_2) check_consistency on switch 00:00:00:00:00:00:00:01 is done
kytos $>
```

- Testing out with an alien flow, 6ms after in the same cycle the alien flow was detected:

```
2022-10-24 11:06:50,899 - INFO [kytos.napps.kytos/flow_manager] [main.py:336:check_consistency] (thread_pool_sb_0) check_consistency on switch 00:00:00:00:00:00:00:01 is done
2022-10-24 11:06:51,699 - INFO [kytos.core.atcp_server] [atcp_server.py:182:connection_lost] (MainThread) Connection lost with client 127.0.0.1:57612. Reason: Request closed by client
2022-10-24 11:07:10,153 - INFO [kytos.core.atcp_server] [atcp_server.py:131:connection_made] (MainThread) New connection from 127.0.0.1:37000
2022-10-24 11:07:10,663 - INFO [kytos.napps.kytos/of_core] [main.py:138:handle_features_reply] (thread_pool_sb_2) Connection ('127.0.0.1', 37000), Switch 00:00:00:00:00:00:00:01: OPENFLO
W HANDSHAKE COMPLETE
2022-10-24 11:07:10,692 - INFO [kytos.napps.kytos/flow_manager] [main.py:571:_send_flow_mods_from_request] (Thread-102) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command:
add, force: False, flows_dict: {'flows': [{'priority': 1000, 'table_id': 0, 'cookie': 12321848580485677057, 'match': {'dl_type': 35020, 'dl_vlan': 3799}, 'actions': [{'action_type': 'out
put', 'port': 4294967293}]}]}
2022-10-24 11:07:10,698 - INFO [werkzeug] [_internal.py:225:_log] (Thread-102) 127.0.0.1 - - [24/Oct/2022 11:07:10] "POST /api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01 HTTP/1.
1" 202 -
kytos $>

kytos $> 2022-10-24 11:07:12,203 - INFO [kytos.napps.kytos/flow_manager] [main.py:333:check_consistency] (thread_pool_sb_0) check_consistency on switch 00:00:00:00:00:00:00:01 has starte
d
2022-10-24 11:07:12,209 - INFO [kytos.napps.kytos/flow_manager] [main.py:408:check_alien_flows] (thread_pool_sb_0) Consistency check: alien flow on switch 00:00:00:00:00:00:00:01
2022-10-24 11:07:12,210 - INFO [kytos.napps.kytos/flow_manager] [main.py:413:check_alien_flows] (thread_pool_sb_0) Flow forwarded to switch 00:00:00:00:00:00:00:01 to be deleted. Flow: {
'flows': [{'switch': '00:00:00:00:00:00:00:01', 'table_id': 0, 'match': {'in_port': 1}, 'priority': 1000, 'idle_timeout': 0, 'hard_timeout': 0, 'cookie': 4097, 'id': '13bc34e4a7a3d61cd0d
0ebb7c49991ff', 'stats': {'byte_count': 0, 'duration_sec': 9, 'duration_nsec': 789000000, 'packet_count': 0}, 'cookie_mask': 0, 'instructions': [{'instruction_type': 'apply_actions', 'ac
tions': [{'port': 2, 'action_type': 'output'}]}]}]}
2022-10-24 11:07:12,217 - INFO [kytos.napps.kytos/flow_manager] [main.py:336:check_consistency] (thread_pool_sb_0) check_consistency on switch 00:00:00:00:00:00:00:01 is done
kytos $>

```

### Using the current master branch

- Notice below that it took more than one consistency check cycle to confirm that it was missing (so, it wasn't taking advantage of this initial iteration that could've been react promptly):

```
kytos $> 2022-10-24 11:16:58,262 - INFO [kytos.core.atcp_server] [atcp_server.py:131:connection_made] (MainThread) New connection from 127.0.0.1:37328
2022-10-24 11:16:58,770 - INFO [kytos.napps.kytos/of_core] [main.py:138:handle_features_reply] (thread_pool_sb_0) Connection ('127.0.0.1', 37328), Switch 00:00:00:00:00:00:00:01: OPENFL
OW HANDSHAKE COMPLETE
2022-10-24 11:16:58,807 - INFO [kytos.napps.kytos/flow_manager] [main.py:569:_send_flow_mods_from_request] (Thread-93) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command:
add, force: False, flows_dict: {'flows': [{'priority': 1000, 'table_id': 0, 'cookie': 12321848580485677057, 'match': {'dl_type': 35020, 'dl_vlan': 3799}, 'actions': [{'action_type': 'ou
tput', 'port': 4294967293}]}]}
2022-10-24 11:16:58,814 - INFO [werkzeug] [_internal.py:225:_log] (Thread-93) 127.0.0.1 - - [24/Oct/2022 11:16:58] "POST /api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01 HTTP/1.
1" 202 -
2022-10-24 11:17:00,298 - INFO [kytos.napps.kytos/flow_manager] [main.py:331:check_consistency] (thread_pool_sb_2) check_consistency on switch 00:00:00:00:00:00:00:01 has started
2022-10-24 11:17:00,308 - INFO [kytos.napps.kytos/flow_manager] [main.py:334:check_consistency] (thread_pool_sb_2) check_consistency on switch 00:00:00:00:00:00:00:01 is done
kytos $>
kytos $>

kytos $> 2022-10-24 11:18:27,804 - INFO [kytos.napps.kytos/flow_manager] [main.py:331:check_consistency] (thread_pool_sb_0) check_consistency on switch 00:00:00:00:00:00:00:01 has start
ed
2022-10-24 11:18:27,816 - INFO [kytos.napps.kytos/flow_manager] [main.py:359:check_missing_flows] (thread_pool_sb_0) Consistency check: missing flow on switch 00:00:00:00:00:00:00:01.
2022-10-24 11:18:27,821 - INFO [kytos.napps.kytos/flow_manager] [main.py:363:check_missing_flows] (thread_pool_sb_0) Flow forwarded to switch 00:00:00:00:00:00:00:01 to be installed. Fl
ow: {'flows': [{'cookie': 0, 'match': {'in_port': 1, 'dl_vlan': 105}, 'actions': [{'action_type': 'output', 'port': 1}], 'table_id': 0, 'priority': 101, 'idle_timeout': 0, 'hard_timeout
': 0}]}
2022-10-24 11:18:27,822 - INFO [kytos.napps.kytos/flow_manager] [main.py:334:check_consistency] (thread_pool_sb_0) check_consistency on switch 00:00:00:00:00:00:00:01 is done
kytos $>
```

### CODE REVIEW

**Comment by viniarck** [comment]
I'll also run e2e tests with this PR.

**Review by italovalcy — APPROVED** [review]
Good catch, @viniarck ! It looks good to me! Please share the results of the e2e tests when you have them.

**Comment by viniarck** [comment]
> Good catch, @viniarck ! It looks good to me! Please share the results of the e2e tests when you have them.

Thanks for reviewing, @italovalcy. Sure thing, it's on https://github.com/amlight/kytos-end-to-end-tests/pull/178, once you have more feedback about that PR let's continue this conversation on that one, thanks.

**Comment by viniarck** [comment]
> > Good catch, @viniarck ! It looks good to me! Please share the results of the e2e tests when you have them.
> 
> Thanks for reviewing, @italovalcy. Sure thing, it's on [amlight/kytos-end-to-end-tests#178](https://github.com/amlight/kytos-end-to-end-tests/pull/178), once you have more feedback about that PR let's continue this conversation on that one, thanks.

I've also run it again locally, isolated from this e2e branch since that branch was also validating a new e2e change, so, I'll go ahead and merge this, and then we'll continue on that one, thanks, Italo:

```
❯ docker logs kytos-end-to-end-tests-kytos-1
Starting enhanced syslogd: rsyslogd.
/etc/openvswitch/conf.db does not exist ... (warning).
Creating empty database /etc/openvswitch/conf.db.
Starting ovsdb-server.
Configuring Open vSwitch system IDs.
Starting ovs-vswitchd.
Enabling remote OVSDB managers.
+ sed -i 's/STATS_INTERVAL = 60/STATS_INTERVAL = 3/g' /var/lib/kytos/napps/kytos/of_core/settings.py
+ sed -i 's/CONSISTENCY_MIN_VERDICT_INTERVAL =.*/CONSISTENCY_MIN_VERDICT_INTERVAL = 3/g' /var/lib/kytos/napps/kytos/flow_manager/settings.py
+ sed -i 's/LINK_UP_TIMER = 10/LINK_UP_TIMER = 1/g' /var/lib/kytos/napps/kytos/topology/settings.py
+ sed -i 's/DEPLOY_EVCS_INTERVAL = 60/DEPLOY_EVCS_INTERVAL = 5/g' /var/lib/kytos/napps/kytos/mef_eline/settings.py
+ sed -i 's/LLDP_LOOP_ACTIONS = \["log"\]/LLDP_LOOP_ACTIONS = \["disable","log"\]/' /var/lib/kytos/napps/kytos/of_lldp/settings.py
+ sed -i 's/LLDP_IGNORED_LOOPS = {}/LLDP_IGNORED_LOOPS = {"00:00:00:00:00:00:00:01": \[\[4, 5\]\]}/' /var/lib/kytos/napps/kytos/of_lldp/settings.py
+ sed -i 's/CONSISTENCY_COOKIE_IGNORED_RANGE =.*/CONSISTENCY_COOKIE_IGNORED_RANGE = [(0xdd00000000000000, 0xdd00000000000009)]/g' /var/lib/kytos/napps/kytos/flow_manager/settings.py
+ sed -i 's/LIVENESS_DEAD_MULTIPLIER =.*/LIVENESS_DEAD_MULTIPLIER = 3/g' /var/lib/kytos/napps/kytos/of_lldp/settings.py
+ kytosd --help
+ sed -i s/WARNING/INFO/g /etc/kytos/logging.ini
+ test -z ''
+ TESTS=tests/
+ python3 scripts/wait_for_mongo.py
Trying to run hello command on MongoDB...
Trying to run 'hello' command on MongoDB...
Trying to run 'hello' command on MongoDB...
Ran 'hello' command on MongoDB successfully. It's ready!
+ for i in {1..1}
+ echo 'iter 1'
+ python3 -m pytest tests/ --timeout=300 -k flow_manager
iter 1
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tests
plugins: timeout-2.0.2
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 208 items / 152 deselected / 56 selected

tests/test_e2e_20_flow_manager.py ................                       [ 28%]
tests/test_e2e_21_flow_manager.py ..                                     [ 32%]
tests/test_e2e_22_flow_manager.py ...............                        [ 58%]
tests/test_e2e_23_flow_manager.py X......................                [100%]

------------------------------- start/stop times -------------------------------
=== 55 passed, 152 deselected, 1 xpassed, 137 warnings in 2833.64s (0:47:13) ===
+ tail -f
```

**Pull request merged**
